// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SolicitorScraper.Infrastructure.Persistence;

#nullable disable

namespace SolicitorScraper.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260716142430_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SolicitorScraper.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsEnabled = true,
                            Name = "London"
                        },
                        new
                        {
                            Id = 2,
                            IsEnabled = true,
                            Name = "Birmingham"
                        },
                        new
                        {
                            Id = 3,
                            IsEnabled = true,
                            Name = "Leeds"
                        },
                        new
                        {
                            Id = 4,
                            IsEnabled = true,
                            Name = "Manchester"
                        },
                        new
                        {
                            Id = 5,
                            IsEnabled = true,
                            Name = "Sheffield"
                        },
                        new
                        {
                            Id = 6,
                            IsEnabled = true,
                            Name = "Bradford"
                        },
                        new
                        {
                            Id = 7,
                            IsEnabled = true,
                            Name = "Liverpool"
                        },
                        new
                        {
                            Id = 8,
                            IsEnabled = true,
                            Name = "Bristol"
                        });
                });

            modelBuilder.Entity("SolicitorScraper.Domain.Entities.SearchRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<string>>("FailedLocations")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SearchRuns");
                });

            modelBuilder.Entity("SolicitorScraper.Domain.Entities.SolicitorResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProfileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("QualityMarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(2, 1)
                        .HasColumnType("numeric(2,1)");

                    b.Property<int?>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<int>("SearchRunId")
                        .HasColumnType("integer");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("SearchRunId", "Location");

                    b.ToTable("SolicitorResults");
                });

            modelBuilder.Entity("SolicitorScraper.Domain.Entities.SolicitorResult", b =>
                {
                    b.HasOne("SolicitorScraper.Domain.Entities.SearchRun", null)
                        .WithMany("Results")
                        .HasForeignKey("SearchRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SolicitorScraper.Domain.Entities.SearchRun", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
