CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Locations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "IsEnabled" boolean NOT NULL,
    CONSTRAINT "PK_Locations" PRIMARY KEY ("Id")
);

CREATE TABLE "SearchRuns" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StartedAt" timestamp with time zone NOT NULL,
    "CompletedAt" timestamp with time zone,
    "FailedLocations" text[] NOT NULL,
    CONSTRAINT "PK_SearchRuns" PRIMARY KEY ("Id")
);

CREATE TABLE "SolicitorResults" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SearchRunId" integer NOT NULL,
    "Location" character varying(100) NOT NULL,
    "Name" character varying(255) NOT NULL,
    "Phone" character varying(50),
    "Address" character varying(500),
    "Website" character varying(500),
    "ProfileUrl" character varying(500),
    "Description" text,
    "QualityMarks" character varying(500),
    "Rating" numeric(2,1),
    "ReviewCount" integer,
    "IsFeatured" boolean NOT NULL,
    CONSTRAINT "PK_SolicitorResults" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SolicitorResults_SearchRuns_SearchRunId" FOREIGN KEY ("SearchRunId") REFERENCES "SearchRuns" ("Id") ON DELETE CASCADE
);

INSERT INTO "Locations" ("Id", "IsEnabled", "Name")
VALUES (1, TRUE, 'London');
INSERT INTO "Locations" ("Id", "IsEnabled", "Name")
VALUES (2, TRUE, 'Birmingham');
INSERT INTO "Locations" ("Id", "IsEnabled", "Name")
VALUES (3, TRUE, 'Leeds');
INSERT INTO "Locations" ("Id", "IsEnabled", "Name")
VALUES (4, TRUE, 'Manchester');
INSERT INTO "Locations" ("Id", "IsEnabled", "Name")
VALUES (5, TRUE, 'Sheffield');
INSERT INTO "Locations" ("Id", "IsEnabled", "Name")
VALUES (6, TRUE, 'Bradford');
INSERT INTO "Locations" ("Id", "IsEnabled", "Name")
VALUES (7, TRUE, 'Liverpool');
INSERT INTO "Locations" ("Id", "IsEnabled", "Name")
VALUES (8, TRUE, 'Bristol');

CREATE UNIQUE INDEX "IX_Locations_Name" ON "Locations" ("Name");

CREATE INDEX "IX_SolicitorResults_SearchRunId_Location" ON "SolicitorResults" ("SearchRunId", "Location");

SELECT setval(
    pg_get_serial_sequence('"Locations"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Locations") + 1,
        nextval(pg_get_serial_sequence('"Locations"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260716142430_Initial', '8.0.17');

COMMIT;

